### ISSUE TITLE
windll is Windows specific. Program won't run on other non-Windows enviroments.

### ISSUE THREAD

**Issue by michaeldkebede** [sourhub226/image-processing-gui#2]
I tried running the program on linux and I got this error:
`ctypes.windll.shcore.SetProcessDpiAwareness(True)
AttributeError: module 'ctypes' has no attribute 'windll'`

After looking around on the internet it seems that the windll module is windows specific.

**Comment by sourhub226** [comment]
Yes. I am aware of this issue. At college, I mostly use Windows, so I have used that statement to temporarily fix Tkinter's DPI scaling (for HiDPI displays). On Linux, one can simply comment it out and proceed.
